---
spring:
  application.name: sample-boot-micro
  aop.proxy-target-class: true
  messages.basename: messages-validation, messages
  cache.jcache.config: ehcache.xml
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
  http.multipart:
    max-file-size: 20MB
    max-request-size: 20MB

banner.location: banner.txt

logging.config: classpath:logback-spring.xml

server:
  port: 8080
  error:
    whitelabel.enabled: false
    path: /api/error

security:
  basic.enabled: false
  user.password: unused

management:
  context-path: /api/management
  security.enabled: false
  health:
    diskspace.enabled: true
    db.enabled: true

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

extension:
  datasource:
    default:
      url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:
      jpa:
        package-to-scan: sample.model
        show-sql: false
        hibernate.ddl-auto: none
    system:
      url: jdbc:h2:tcp://localhost:9092/mem:system
      username: sa
      password:
      jpa:
        package-to-scan: sample.context
        show-sql: false
        hibernate.ddl-auto: none

---
spring:
  profiles: production

management.security.enabled: true

extension:
  datasource:
    default:
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
    system:
      url: jdbc:oracle:thin:@xxx.xxx.xxx.xxx:1521:xx
      username: XXXXXX
      password: XXXXXX
